# -*- coding: utf-8 -*-
"""CHDModel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xP-u0JkLjL1MU0BfcWtR3NoqaxYhkShu
"""

# Commented out IPython magic to ensure Python compatibility.
try:
  # %tensorflow_version only exists in Colab.
#   %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf
import pandas as pd
from sklearn.model_selection import train_test_split

dataset_url = 'heart.csv'
data = pd.read_csv(dataset_url)
print(data.head())

"""Split data into training set, test set, and validation set"""

train, test = train_test_split(data, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)
print(len(train), 'train examples')
print(len(val), 'validation examples')
print(len(test), 'test examples')

TRAIN_LEN = len(train)
VAL_LEN = len(val)
TEST_LEN = len(test)

"""Pre-process Data"""

# A utility method to create a tf.data dataset from a Pandas Dataframe
# This function was taken from https://www.tensorflow.org/tutorials/structured_data/feature_columns#create_a_feature_layer
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop('chd')
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  return ds

train_ds = df_to_dataset(train)
val_ds = df_to_dataset(val, shuffle=False)
test_ds = df_to_dataset(test, shuffle=False)

for feature_batch, label_batch in train_ds.take(1):
  print('Every feature:', list(feature_batch.keys()))
  print('A batch of ages:', feature_batch['age'])
  print('A batch of targets:', label_batch )

feature_columns = []

# numeric cols
for header in ['row.names', 'sbp', 'tobacco', 'ldl', 'adiposity', 'typea', 'obesity', 'alcohol', 'age']:
  feature_columns.append(tf.feature_column.numeric_column(header))

# categorical col
data["famhist"] = data["famhist"].apply(str)
famhist = tf.feature_column.categorical_column_with_vocabulary_list(
      'famhist', ['0', '1'])
famhist_one_hot = tf.feature_column.indicator_column(famhist)
feature_columns.append(famhist_one_hot)

"""Building and Training the Model"""

feature_layer = tf.keras.layers.DenseFeatures(feature_columns)

batch_size = 32
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)


model = tf.keras.Sequential([
  feature_layer,
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(rate=0.2),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(train_ds,
          validation_data=val_ds,
          epochs=20)

print(f"---- Evaluate TEST SET ----")
loss, accuracy = model.evaluate(test_ds)
print(f"Model Loss:    {loss:.2f}")
print(f"Model Accuracy: {accuracy*100:.1f}%")

print(f"---- Evaluate TRAIN SET ----")
loss, accuracy = model.evaluate(train_ds)
print(f"Model Loss:    {loss:.2f}")
print(f"Model Accuracy: {accuracy*100:.1f}%")

print(f"---- Evaluate VALIDATION SET ----")
loss, accuracy = model.evaluate(val_ds)
print(f"Model Loss:    {loss:.2f}")
print(f"Model Accuracy: {accuracy*100:.1f}%")